techpack: Display: Mark dsi_display_dispUtil_prepare & dsi_panel_set_local_hbm_param as maybe unused
../../../../../../kernel/motorola/sm7325/techpack/display/msm/dsi/dsi_display.c:1127:12: error: unused function 'dsi_display_dispUtil_prepare' [-Werror,-Wunused-function]
static int dsi_display_dispUtil_prepare(const char *cmd_buf, u32 cmd_buf_len,
           ^
1 error generated.
make[4]: *** [/home/themard/android/lineage-21/kernel/motorola/sm7325/scripts/Makefile.build:288: techpack/display/msm/dsi/dsi_display.o] Error 1
make[4]: *** Waiting for unfinished jobs....
../../../../../../kernel/motorola/sm7325/techpack/display/msm/dsi/dsi_panel.c:1045:12: error: unused function 'dsi_panel_set_local_hbm_param' [-Werror,-Wunused-function]
static int dsi_panel_set_local_hbm_param(struct dsi_panel *panel,
           ^
1 error generated.

Change-Id: I94a90a719871db2a7230c1308847c058ed9f397b