techpack: audio: aw88261: solve unused variable error
techpack/audio/asoc/codecs/aw88261/aw882xx.c:1289:20:
error: variable 'aw_dev' set but not used [-Werror,-Wunused-but-set-variable]
        struct aw_device *aw_dev;

Change-Id: I9a3acd6070f8b7e10afce76e82768ab78262dc27